version: '3.8'
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php-apache
    volumes:
      - ./scripts/serverside:/var/www/html/
    ports:
      - 8000:80