version: '3.8'
services:
  backend:
    build:
      context: ./
      dockerfile: backend.Dockerfile
    container_name: backend
    volumes:
      - ./scripts/serverside:/var/www/html/
    ports:
      - 8000:80
  composer:
    image: composer
    container_name: composer
    volumes:
      - ./scripts/serverside:/var/www/html/
    working_dir: /var/www/html/
    command: install
  frontend:
    build:
      context: ./
      dockerfile: frontend.Dockerfile
    container_name: frontend
    volumes:
      - ./scripts/clientside:/var/www/html/
    ports:
      - 8080:80